export const FETCH_PROJECTS_LIST_START = "FETCH_PROJECTS_LIST_START";
export const FETCH_PROJECTS_LIST_SUCCESS = "FETCH_PROJECTS_LIST_SUCCESS";
export const FETCH_PROJECTS_LIST_FAIL = "FETCH_PROJECTS_LIST_FAIL";
