export const FETCH_PROJECTS_LIST_START = "FETCH_PROJECTS_LIST_START";
export const FETCH_PROJECTS_LIST_SUCCESS = "FETCH_PROJECTS_LIST_SUCCESS";
export const FETCH_PROJECTS_LIST_FAIL = "FETCH_PROJECTS_LIST_FAIL";

export const CREATE_PROJECT_REQUEST = "CREATE_PROJECT_REQUEST";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAIL = "CREATE_PROJECT_FAIL";

export const DELETE_PROJECT_REQUEST = "DELETE_PROJECT_REQUEST";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAIL = "DELETE_PROJECT_FAIL";

export const UPDATE_PERSON_ROLE_REQUEST = "UPDATE_PERSON_ROLE_REQUEST";
export const UPDATE_PERSON_ROLE_SUCCESS = "UPDATE_PERSON_ROLE_SUCCESS";
export const UPDATE_PERSON_ROLE_FAIL = "UPDATE_PERSON_ROLE_FAIL";

export const UPDATE_PERSON_PASS_REQUEST = "UPDATE_PERSON_PASS_REQUEST";
export const UPDATE_PERSON_PASS_SUCCESS = "UPDATE_PERSON_PASS_SUCCESS";
export const UPDATE_PERSON_PASS_FAIL = "UPDATE_PERSON_PASS_FAIL";

export const UPDATE_PERSON_EMAIL_REQUEST = "UPDATE_PERSON_EMAIL_REQUEST";
export const UPDATE_PERSON_EMAIL_SUCCESS = "UPDATE_PERSON_EMAIL_SUCCESS";
export const UPDATE_PERSON_EMAIL_FAIL = "UPDATE_PERSON_EMAIL_FAIL";

export const REGISTER_PERSON_REQUEST = "REGISTER_PERSON_REQUEST";
export const REGISTER_PERSON_SUCCESS = "REGISTER_PERSON_SUCCESS";
export const REGISTER_PERSON_FAIL = "REGISTER_PERSON_FAIL";

export const LOGIN_PERSON_REQUEST = "LOGIN_PERSON_REQUEST";
export const LOGIN_PERSON_SUCCESS = "LOGIN_PERSON_SUCCESS";
export const LOGIN_PERSON_FAIL = "LOGIN_PERSON_FAIL";

export const GET_ALL_PEOPLE_REQUEST = "GET_ALL_PEOPLE_REQUEST";
export const GET_ALL_PEOPLE_SUCCESS = "GET_ALL_PEOPLE_SUCCESS";
export const GET_ALL_PEOPLE_FAIL = "GET_ALL_PEOPLE_FAIL";

export const ADMIN_TOKEN_REQUEST = "ADMIN_TOKEN_REQUEST";
export const ADMIN_TOKEN_SUCCESS = "ADMIN_TOKEN_SUCCESS";
export const ADMIN_TOKEN_FAIL = "ADMIN_TOKEN_FAIL";

export const UPDATE_PROJECT_REQUEST = "UPDATE_PROJECT_REQUEST";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_FAIL = "UPDATE_PROJECT_FAIL";
