export const UPDATE_STUDY_TYPE_REQUEST = "UPDATE_STUDY_TYPE_REQUEST";
export const UPDATE_STUDY_TYPE_SUCCESS = "UPDATE_STUDY_TYPE_SUCCESS";
export const UPDATE_STUDY_TYPE_FAIL = "UPDATE_STUDY_TYPE_FAIL";

export const JOIN_STUDENT_TO_PROJECT_REQUEST =
  "JOIN_STUDENT_TO_PROJECT_REQUEST";
export const JOIN_STUDENT_TO_PROJECT_SUCCESS =
  "JOIN_STUDENT_TO_PROJECT_SUCCESS";
export const JOIN_STUDENT_TO_PROJECT_FAIL = "JOIN_STUDENT_TO_PROJECT_FAIL";

export const GET_STUDENT_BY_EMAIL_REQUEST = "GET_STUDENT_BY_EMAIL_REQUEST";
export const GET_STUDENT_BY_EMAIL_SUCCESS = "GET_STUDENT_BY_EMAIL_SUCCESS";
export const GET_STUDENT_BY_EMAIL_FAIL = "GET_STUDENT_BY_EMAIL_FAIL";

export const ADD_STUDENT_REQUEST = "ADD_STUDENT_REQUEST";
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";
export const ADD_STUDENT_FAIL = "ADD_STUDENT_FAIL";

export const GET_ALL_STUDENTS_REQUEST = "GET_ALL_STUDENTS_REQUEST";
export const GET_ALL_STUDENTS_SUCCESS = "GET_ALL_STUDENTS_SUCCESS";
export const GET_ALL_STUDENTS_FAIL = "GET_ALL_STUDENTS_FAIL";
